### ISSUE TITLE
Improve documentation for JSDoc

### ISSUE THREAD

**Issue by pdud** [lifeart/els-addon-typed-templates#17]
Thanks for the awesome addon!

I'm using it in a ember-cli js only project (no ts) and trying to get it to work with JSDoc as mentioned in the README. 

I am new to JSDoc but I can get it to work in a glimmer component with JSDoc that looks like this:

```js
import Component from '@glimmer/component';

/**
 * @typedef Args
 * @type {object}
 * @property {String} firstName
 * @property {String} lastName
 */

export default class MyComponent extends Component {
  /** @return {Args} */
  get args() {
    return this.super(...arguments);
  }

  get name() {
    return `${this.args.firstName} ${this.args.lastName};
  }
}
```

Is this what you had in mind to use JSDoc? It's a bit inconvenient overwriting arguments.

I'd happily get in a pull request to help improve the documentation with your recommendation.

**Comment by lifeart** [comment]
Hi, @pdud! Thank you for issue!

I think you can use another way to specify args - https://github.com/lifeart/els-addon-typed-templates/blob/master/README.md#how-to-get-args-checking-for-template-only-components (describe args interface in comment inside template)

Interface  must  have name “Args”

I believe you can use imports inside interface descriptor (on the top)

**Comment by pdud** [comment]
Thanks for your reply!!

Ah that works very well for me if it just a template. As soon as I add a component.js file it stops working.

## Just hbs file with interface Args
- Correctly validates args.firstName and args.lastName exist
- Correctly validates args.age does not exist

<img width="617" alt="Screen Shot 2020-02-19 at 10 09 50 AM" src="https://user-images.githubusercontent.com/435890/74856307-ee8c2c00-530f-11ea-8c58-ecd0ff20f99b.png">

## hbs file with glimmer component and interface Args in hbs file
- Incorrectly validates args.firstName and args.lastName don’t exist
- Correctly validates this.name exists
- Correctly validates this.age exists

<img width="460" alt="Screen Shot 2020-02-19 at 10 12 05 AM" src="https://user-images.githubusercontent.com/435890/74856324-f2b84980-530f-11ea-8d54-408210cea174.png">

**Comment by lifeart** [comment]
@pdud try `2.2.15`
fixes: https://github.com/lifeart/els-addon-typed-templates/commit/15ac1b66da793cb9e6dc7dfccb8238bd792b56f5

**Comment by pdud** [comment]
Thank you so much! Documenting the interface in the template works very nicely!!

Now there are two options that work very well for non typescript projects.

1. Document in the template using interface (works with or without component.js)

2. Document with JSDoc as above
- this one has the added benefit of autocompleting inside the component.js and template.hbs

Do you know of a different supported way to document a component.js file via JSDoc where I don't have to overwrite the args getter?

```js
/** @return {Args} */
get args() {
  return this.super(...arguments);
}
```

**Comment by lifeart** [comment]
for now, suddently, have no idea, I'm trying few different ways, but no luck :(

and I able to get working same construction as described above
```js
/**
 * @typedef {Object} Args
 * @property {string} foo
 */
class Foo extends Boo {
    /** @return {Args} */
    get args() {
        return this.super(...arguments);
    }
}
```

**Comment by pdud** [comment]
Thank you so much for looking into it!

Would you be interested if I submitted a pull request to update the documentation with some our discussions here?

**Comment by lifeart** [comment]
@pdud sure, you are welcome!

**Comment by lifeart** [comment]
@pdud I'm thinking about args, and looks like this code should work:

```js
/**
 * @typedef {Object} Args
 * @property {object} boo
 * @property {string} boo.foo
 * @property {boolean} activeTab;
 */

export default class ProductTabsComponent extends Component {
    /**
     * @type {Args}
     */
    args;
}
```

**Comment by pdud** [comment]
Thanks @lifeart - we're in the middle of upgrading our components to Glimmer and this addon has helped a lot with the upgrade!

I have not forgot and will put in a pull request to update some of the documentation with what I have experienced from our discussions!

**Comment by lifeart** [comment]
![D35A9F7A-D785-4353-8DCA-5CDCD8936593](https://user-images.githubusercontent.com/1360552/75178783-cd7d6e00-5749-11ea-9091-884658e4fbb2.jpeg)

This is one more way to mention arguments. Use latest typed-templates and glimmer-syntax extension

**Comment by lifeart** [comment]
@pdud could you test this syntax?

![image](https://user-images.githubusercontent.com/1360552/82561299-cf55a280-9b7b-11ea-86fb-90e26beabe8e.png)

**Comment by pdud** [comment]
Awesome! 😎 Yes it works well! I prefer this new rather than overwriting args.

This also works

```js
/**
 * @typedef {Object} Args
 * @property {String} foo
 *
 * @extends Component<Args>
 * */
export default class MyComponent extends Component {
}
```

**Comment by lifeart** [comment]
readme updated

**Comment by pdud** [comment]
Love it! Thanks for all your work on this!

**Comment by pdud** [comment]
I have a hard time in template only components getting ember data models (no typescript) to autocomplete using absolute paths like `'pizza/models/user'`.

Any ideas? :)

## Doesn't work

```hbs
{{!--
  <script @typedef>
    import User from 'pizza/models/user';

    interface Args {
      user: User
    }
  </script>
--}}


{{@user.}}
```


## Works

It works using a relative path like shown in the documentation.

```hbs
{{!--
  <script @typedef>
    import User from './../../models/user';

    interface Args {
      user: User
    }
  </script>
--}}


{{@user.}}
```
