### ISSUE TITLE
No autocomplete for another components arguments

### ISSUE THREAD

**Issue by emattias** [lifeart/els-addon-typed-templates#19]
I have defined a components `@activeTab` argument:

```js
/**
 * @typedef {Object} Args
 * @property {boolean} activeTab;
 */
export default class Button extends Component {
  /**
   * @type {Args}
   */
  args;
}
```
I do get it suggested in this components template `button.hbs`:

<img width="524" alt="CleanShot 2020-05-20 at 10 57 39@2x" src="https://user-images.githubusercontent.com/351537/82426932-bd470780-9a88-11ea-9332-b598f60bdbd3.png">
but when I use that component in another template I dont get it suggested:

<img width="544" alt="CleanShot 2020-05-20 at 10 55 55@2x" src="https://user-images.githubusercontent.com/351537/82426731-82dd6a80-9a88-11ea-8b0c-ce614c3bc66b.png">

Here's a reproduction repo: https://github.com/emattias/els-addon-typed-templates-no-suggestions-repro/tree/master/app/components

**Comment by pdud** [comment]
@emattias as an aside I had issues documenting args like that.

https://github.com/lifeart/els-addon-typed-templates/pull/18#issue-382705337

Either way, lifeart shared a nicer way of doing it today.

```js
/**
 * @typedef {Object} Args
 * @property {boolean} activeTab;
 * @extends Component<Args>
 */
export default class Button extends Component {}
```
