### ISSUE TITLE
Can not recognize property names that include "-" chars

### ISSUE THREAD

**Issue by nightire** [lifeart/els-addon-typed-templates#39]
![image](https://user-images.githubusercontent.com/1104018/105828548-39252680-5ffe-11eb-9e63-4c0a3f168dd5.png)

**Comment by nightire** [comment]
![image](https://user-images.githubusercontent.com/1104018/105829049-d3856a00-5ffe-11eb-83c4-e1b26857b92c.png)

I understand `xx-xxx` is not an ideal property name, but unfortunately, I have to deal with it in some legacy projects.

**Comment by lifeart** [comment]
yeah, it's fixable case

**Comment by lifeart** [comment]
@nightire adressed in https://github.com/lifeart/els-addon-typed-templates/pull/26/commits/ac14485c3a320420f817a3537395cefc6e38f2e3

**Comment by lifeart** [comment]
v 4.0.0
