### ISSUE TITLE
Incorrectly expects the argument to `async-await` to be an array

### ISSUE THREAD

**Issue by wagenet** [lifeart/els-addon-typed-templates#59]
https://github.com/tildeio/ember-async-await-helper

**Comment by wagenet** [comment]
Looks like I can overwrite this:
```ts
declare module 'ember-typed-templates' {
  interface GlobalRegistry {
    'async-await': <T>(params: T | Promise<T>) => T;
  }
}
```

I'm still not sure why it's the default.

**Comment by wagenet** [comment]
I think I misunderstood how this works.

**Comment by lifeart** [comment]
@wagenet if you have correct typings for this helper - we could add it to repo

**Comment by wagenet** [comment]
See #78
