### ISSUE TITLE
Cursed comment

### ISSUE THREAD

**Issue by wagenet** [lifeart/els-addon-typed-templates#61]
```hbs
{{!--
a
the the
--}}
{{#each (array @model)}}

{{/each}}
```

This causes: `Duplicate identifier 'the'.`

**Comment by wagenet** [comment]
May be the same issue referred to in #41.

**Comment by lifeart** [comment]
Yeah, likely we have to handle comments In more safer way, it’s happens because we support type definitions inside it

**Comment by lifeart** [comment]
should be fixed in v4.2.3
